services:
  - name: api
    type: web
    repo: https://github.com/xxxurya/Mine-chest.git
    branch: master
    dockerfilePath: Dockerfile
    dockerCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
